// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RutasBackend.Data;

#nullable disable

namespace RutasBackend.Data.Migrations.Bd
{
    [DbContext(typeof(BdContext))]
    [Migration("20260224224452_AddCitizenUserIdToAction")]
    partial class AddCitizenUserIdToAction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RutasBackend.Models.Bd.CitizenUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CamouflageMode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HardwareAlertsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LocalUserProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OfficialEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PinCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CitizenUsers", t =>
                        {
                            t.HasTrigger("CitizenUsers_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RutasBackend.Models.Bd.CitizenUserAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CitizenUserActionType")
                        .HasColumnType("int");

                    b.Property<Guid>("CitizenUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OfficialEntityUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CitizenUserId");

                    b.HasIndex("OfficialEntityUserId");

                    b.ToTable("CitizenUserActions", t =>
                        {
                            t.HasTrigger("CitizenUserActions_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RutasBackend.Models.Bd.CompanionSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanionUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("EndLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("EndLongitude")
                        .HasColumnType("float");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JourneyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("StartLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("StartLongitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId");

                    b.ToTable("CompanionSegments", t =>
                        {
                            t.HasTrigger("CompanionSegments_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RutasBackend.Models.Bd.Journey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CitizenUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DestinationLatitude")
                        .HasColumnType("float");

                    b.Property<double>("DestinationLongitude")
                        .HasColumnType("float");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("StartLatitude")
                        .HasColumnType("float");

                    b.Property<double>("StartLongitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UsedSafeRoute")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CitizenUserId");

                    b.ToTable("Journeys", t =>
                        {
                            t.HasTrigger("Journeys_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RutasBackend.Models.Bd.OfficialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("OfficialEntities", t =>
                        {
                            t.HasTrigger("OfficialEntities_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RutasBackend.Models.Bd.OfficialEntityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OfficialEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OfficialEntityId");

                    b.ToTable("OfficialEntityUsers", t =>
                        {
                            t.HasTrigger("OfficialEntityUsers_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RutasBackend.Models.Bd.PanicAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CitizenUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EncryptedMediaLocation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("TriggerMethod")
                        .HasColumnType("int");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CitizenUserId");

                    b.ToTable("PanicAlerts", t =>
                        {
                            t.HasTrigger("PanicAlerts_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RutasBackend.Models.Bd.ReportPin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CitizenUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<int>("IssueType")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ReportPins", t =>
                        {
                            t.HasTrigger("ReportPins_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RutasBackend.Models.Bd.SafeHaven", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<bool>("Is24Hours")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("SafeHavens", t =>
                        {
                            t.HasTrigger("SafeHavens_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RutasBackend.Models.Bd.CitizenUserAction", b =>
                {
                    b.HasOne("RutasBackend.Models.Bd.CitizenUser", "CitizenUser")
                        .WithMany("CitizenUserActions")
                        .HasForeignKey("CitizenUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RutasBackend.Models.Bd.OfficialEntityUser", "OfficialEntityUser")
                        .WithMany()
                        .HasForeignKey("OfficialEntityUserId");

                    b.Navigation("CitizenUser");

                    b.Navigation("OfficialEntityUser");
                });

            modelBuilder.Entity("RutasBackend.Models.Bd.CompanionSegment", b =>
                {
                    b.HasOne("RutasBackend.Models.Bd.Journey", "Journey")
                        .WithMany("CompanionSegments")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("RutasBackend.Models.Bd.Journey", b =>
                {
                    b.HasOne("RutasBackend.Models.Bd.CitizenUser", "CitizenUser")
                        .WithMany("Journeys")
                        .HasForeignKey("CitizenUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CitizenUser");
                });

            modelBuilder.Entity("RutasBackend.Models.Bd.OfficialEntityUser", b =>
                {
                    b.HasOne("RutasBackend.Models.Bd.OfficialEntity", "OfficialEntity")
                        .WithMany("OfficialEntityUsers")
                        .HasForeignKey("OfficialEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfficialEntity");
                });

            modelBuilder.Entity("RutasBackend.Models.Bd.PanicAlert", b =>
                {
                    b.HasOne("RutasBackend.Models.Bd.CitizenUser", "CitizenUser")
                        .WithMany()
                        .HasForeignKey("CitizenUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CitizenUser");
                });

            modelBuilder.Entity("RutasBackend.Models.Bd.CitizenUser", b =>
                {
                    b.Navigation("CitizenUserActions");

                    b.Navigation("Journeys");
                });

            modelBuilder.Entity("RutasBackend.Models.Bd.Journey", b =>
                {
                    b.Navigation("CompanionSegments");
                });

            modelBuilder.Entity("RutasBackend.Models.Bd.OfficialEntity", b =>
                {
                    b.Navigation("OfficialEntityUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
