// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RutasBackend.Data;

#nullable disable

namespace RutasBackend.Data.Migrations.Bd
{
    [DbContext(typeof(BdContext))]
    partial class BdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RutasBackend.Models.Bd.OfficialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("OfficialEntities", t =>
                        {
                            t.HasTrigger("OfficialEntities_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RutasBackend.Models.Bd.OfficialEntityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OfficialEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OfficialEntityId");

                    b.ToTable("OfficialEntityUsers", t =>
                        {
                            t.HasTrigger("OfficialEntityUsers_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RutasBackend.Models.Bd.OfficialEntityUser", b =>
                {
                    b.HasOne("RutasBackend.Models.Bd.OfficialEntity", "OfficialEntity")
                        .WithMany("OfficialEntityUsers")
                        .HasForeignKey("OfficialEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfficialEntity");
                });

            modelBuilder.Entity("RutasBackend.Models.Bd.OfficialEntity", b =>
                {
                    b.Navigation("OfficialEntityUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
